# Site settings
title: CLIMB - Cloud Infrastructure for Microbial Bioinformatics
email: info@climb.ac.uk
description: >-
  CLIMB is the UK's leading cloud computing infrastructure originally designed for microbial bioinformatics 
  and now available for the broader scientific community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - scrapbook/
  
# Default layout
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"